cloud:
  aws:
    credentials:
      access: access
      secret: secret
      region: ap-southeast-1
infra:
  aws:
    sqs:
      url: sqs-url
  pusher:
    app-id: app-id
    key: key-id
    secret: secret
    region: region
    encrypted: true
spring:
  application:
    name: mathselfieapp
